In [1]:
import requests

In [2]:
standings_url = "https://fbref.com/en/comps/9/Premier-League-Stats"

In [ ]:
data = requests.get(standings_url)

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
soup = BeautifulSoup(data.text)

In [ ]:
standings_table = soup.select('table.stats_table')[0]

In [ ]:
links = standings_table.find_all('a')

In [ ]:
links = [l.get('href') for l in links]

In [ ]:
links = [l for l in links if '/squads/' in l]

In [ ]:
team_urls = [f"https://fbref.com{l}" for l in links]

In [5]:
team_urls

NameError: name 'team_urls' is not defined

In [ ]:
team_url = team_urls[0]

In [ ]:
data = requests.get(team_url)

In [4]:
import pandas as pd
matches = pd.read_html(data.text, match="Scores & Fixtures")

NameError: name 'data' is not defined

In [10]:
matches[0].head()

NameError: name 'matches' is not defined

In [11]:
soup = BeautifulSoup(data.text)

NameError: name 'BeautifulSoup' is not defined

In [12]:
links = soup.find_all('a')

NameError: name 'soup' is not defined

In [13]:
links = [l.get("href") for l in links]

NameError: name 'links' is not defined

In [19]:
links = [l for l in links if l and 'all_comps/shooting/' in l ]

In [20]:
links

['/en/squads/18bb7c10/2022-2023/matchlogs/all_comps/shooting/Arsenal-Match-Logs-All-Competitions',
 '/en/squads/18bb7c10/2022-2023/matchlogs/all_comps/shooting/Arsenal-Match-Logs-All-Competitions',
 '/en/squads/18bb7c10/2022-2023/matchlogs/all_comps/shooting/Arsenal-Match-Logs-All-Competitions',
 '/en/squads/18bb7c10/2022-2023/matchlogs/all_comps/shooting/Arsenal-Match-Logs-All-Competitions']

In [21]:
data = requests.get(f"https://fbref.com{links[0]}")

In [22]:
shooting = pd.read_html(data.text, match="Shooting")[0]

In [23]:
 shooting.head()

  For Arsenal                                                              \
         Date   Time            Comp        Round  Day Venue Result GF GA
0  2022-08-05  20:00  Premier League  Matchweek 1  Fri  Away      W  2  0
1  2022-08-13  15:00  Premier League  Matchweek 2  Sat  Home      W  4  2
2  2022-08-20  17:30  Premier League  Matchweek 3  Sat  Away      W  3  0
3  2022-08-27  17:30  Premier League  Matchweek 4  Sat  Home      W  2  1
4  2022-08-31  19:30  Premier League  Matchweek 5  Wed  Home      W  2  1

                   ... Standard               Expected                    \
         Opponent  ...     Dist   FK PK PKatt       xG npxG npxG/Sh G-xG
0  Crystal Palace  ...     14.6  1.0  0     0      1.0  1.0    0.10  0.0
1  Leicester City  ...     13.0  0.0  0     0      2.7  2.7    0.16  1.3
2     Bournemouth  ...     14.8  0.0  0     0      1.3  1.3    0.10  1.7
3          Fulham  ...     15.5  1.0  0     0      2.6  2.6    0.12 -0.6
4     Aston Villa  ...     16.3  1.0  0     0      2.4  2.4    0.12 -0.4

          Unnamed: 25_level_0
  np:G-xG        Match Report
0     0.0        Match Report
1     1.3        Match Report
2     1.7        Match Report
3    -0.6        Match Report
4    -0.4        Match Report

[5 rows x 26 columns]

In [24]:
shooting.columns = shooting.columns.droplevel()

In [25]:
shooting.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Match Report
0,2022-08-05,20:00,Premier League,Matchweek 1,Fri,Away,W,2,0,Crystal Palace,...,14.6,1.0,0,0,1.0,1.0,0.10,0.0,0.0,Match Report
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,2,Leicester City,...,13.0,0.0,0,0,2.7,2.7,0.16,1.3,1.3,Match Report
2,2022-08-20,17:30,Premier League,Matchweek 3,Sat,Away,W,3,0,Bournemouth,...,14.8,0.0,0,0,1.3,1.3,0.10,1.7,1.7,Match Report
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2,1,Fulham,...,15.5,1.0,0,0,2.6,2.6,0.12,-0.6,-0.6,Match Report
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2,1,Aston Villa,...,16.3,1.0,0,0,2.4,2.4,0.12,-0.4,-0.4,Match Report

In [26]:
team_data = matches[0].merge(shooting[["Date", "Sh", "SoT", "Dist", "FK", "PK", "PKatt"]], on="Date")

In [27]:
team_data.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Formation,Referee,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt
0,2022-08-05,20:00,Premier League,Matchweek 1,Fri,Away,W,2.0,0.0,Crystal Palace,...,4-3-3,Anthony Taylor,Match Report,NaN,10,2,14.6,1.0,0,0
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,2.0,Leicester City,...,4-3-3,Darren England,Match Report,NaN,19,7,13.0,0.0,0,0
2,2022-08-20,17:30,Premier League,Matchweek 3,Sat,Away,W,3.0,0.0,Bournemouth,...,4-3-3,Craig Pawson,Match Report,NaN,14,6,14.8,0.0,0,0
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,...,4-3-3,Jarred Gillett,Match Report,NaN,22,8,15.5,1.0,0,0
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,...,4-3-3,Robert Jones,Match Report,NaN,22,8,16.3,1.0,0,0

In [28]:
shooting.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Match Report
0,2022-08-05,20:00,Premier League,Matchweek 1,Fri,Away,W,2,0,Crystal Palace,...,14.6,1.0,0,0,1.0,1.0,0.10,0.0,0.0,Match Report
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,2,Leicester City,...,13.0,0.0,0,0,2.7,2.7,0.16,1.3,1.3,Match Report
2,2022-08-20,17:30,Premier League,Matchweek 3,Sat,Away,W,3,0,Bournemouth,...,14.8,0.0,0,0,1.3,1.3,0.10,1.7,1.7,Match Report
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2,1,Fulham,...,15.5,1.0,0,0,2.6,2.6,0.12,-0.6,-0.6,Match Report
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2,1,Aston Villa,...,16.3,1.0,0,0,2.4,2.4,0.12,-0.4,-0.4,Match Report

In [29]:
shooting.shape

(22, 26)

In [30]:
years = list(range(2022, 2020, -1))

In [31]:
years

[2022, 2021]

In [32]:
all_matches = []

In [33]:
standings_url = "https://fbref.com/en/comps/9/Premier-League-Stats"

In [34]:
import time
for year in years:
    data = requests.get(standings_url)
    soup = BeautifulSoup(data.text)
    standings_table = soup.select('table.stats_table')[0]
    
    links = [l.get("href") for l in standings_table.find_all('a')]
    links = [l for l in links if '/squads/' in l]
    team_urls = [f"https://fbref.com{l}" for l in links]
    
    previous_season = soup.select("a.prev")[0].get("href")
    standings_url = f"https://fbref.com/{previous_season}"
    
    for team_url in team_urls:
        team_name = team_url.split("/")[-1].replace("-Stats", "").replace("-", " ")
        
        data = requests.get(team_url)
        matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
        
        soup = BeautifulSoup(data.text)
        links = [l.get("href") for l in soup.find_all('a')]
        links   = [l for l in links if l and 'all_comps/shooting/' in l]
        data = requests.get(f"https://fbref.com{links[0]}")
        shooting = pd.read_html(data.text, match="Shooting")[0]
        shooting.columns = shooting.columns.droplevel()
        
        try:
            team_data = matches.merge(shooting[["Date", "Sh", "SoT", "Dist", "FK", "PK", "PKatt"]], on="Date")
        except ValueError:
            continue
        team_data = team_data[team_data["Comp"] == "Premier League"]
        team_data["Season"] = year
        team_data["Team"] = team_name
        all_matches.append(team_data)
        time.sleep(1)

In [35]:
match_df = pd.concat(all_matches)

In [2]:
match_df,columns = [c.lower() for c in match_df.columns]

NameError: name 'match_df' is not defined

In [3]:
matches_df = pd.read_csv("matches.csv")
matches_df.columns

NameError: name 'pd' is not defined

In [1]:
import mysql.connector

def mysqlconnect():
    # To connect MySQL database
    conn = mysql.connector.connect(host='localhost',
                        database='scrapper',
                        user='root',
                        password='')
    data1 = matches_df['id']
    data2 = matches_df[ 'Date']
    data3 = matches_df['Time']
    data4 = matches_df['Comp']
    data5 = matches_df['Comp']
    data6 = matches_df['Day']
    data7 = matches_df['Venue']
    data8 = matches_df['Result']
    data9 = matches_df['GF']
    data10 = matches_df['GA']
    data11 = matches_df['Opponent']
    data12 = matches_df['xG']
    data13 = matches_df['xGA']
    data14 = matches_df['Poss']
    data15 = matches_df['Attendance']
    data16 = matches_df['Captain']
    data17 = matches_df['Formation']
    data18 = matches_df['Referee']
    data19 = matches_df['Match Report']
    data20 = matches_df['Notes']
    data21 = matches_df['Sh']
    data22 = matches_df['SoT']
    data23 = matches_df['Dist']
    data24 = matches_df['FK']
    data25 = matches_df['PK']
    data26 = matches_df['PKatt']
    data27 = matches_df['Season']
    data28 = matches_df['Team']
    
    try:
        cur = conn.cursor()

        data = """INSERT INTO matches(id,Dates, Times, Comp, Round, Day, Venue, Result, GF, GA, Opponent, xG, xGA, Poss, Attendance, Captain, Formation, Referee, Match_Report, Notes, Sh, SoT, Dist, FK, PK, PKatt, Season, Team) VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"""
        values = (data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12, data13, data14, data15, data16, data17, data18, data19, data20, data21, data23, data24, data25, data26, data27, data28)
        cur.execute(data, values)
        conn.commit()
        # Select query
        cur.execute("select * from matches")
        output = cur.fetchall()
        for i in output:
            print(i)

        # To close the connection
        conn.close()
    except Exception as e:
        print("Error")
  
# Driver Code
if __name__ == "__main__" :
    mysqlconnect()

NameError: name 'matches_df' is not defined